language: node_js
node_js:
- '9'
after_success:
- yarn deploy
env:
  global:
    secure: KPdVtnNBSpPhOZ57yMrgoeBAAJo+h5WfiWJoOdcFjZ2Gx7Yw3z3GruwFeBY0NfggmkDJMNx8/PsY60/J3SskS/Z7HMJI8szXZrHaOumGj97GVZCruxGLBXipsSs9ujpvLc1Q+IPslx2ilKYaY8BhkrzwdAPqW0Xrti6NiqyxIA3cVnXLMrVkyeFOe4g9Yu6tH+Le+EYCtOJsLbGqQdupqDRYIvSu83PFAumE9y3QMZLdppKYCFuWUST0pAVPvOswApgG1omaiK5LvAKgnGBnXPFfHISwWDLyXGkIDYJGLPY/+YQKw5n4WInPAIayZrEaYm+4r/GBceJGWprt+XReiGSOdGACs2U/fBFonxgmk06PLFJ0s32qNkV2ZNxCO7VCNjiw+u2aQuX1I/jOpE9myHvIALv5p+MAEb07Z5vs55no3e/2/w9s7VWoiebHOXblnxc+8elcUOoflIz3fWIMS/ck2eIQe6wbmd12vY7L25cwWirZllvXudedwmb68XFcfhmeiIDFfBbthL+vDwEQ7iLYlMXQmVuhUs/7al0629VANJ47yvUfSmpmsepZWOlhEbL6Llzd6iTsAIhfH6dYm2kycp+2gF0gwjq1elxxqlspqF89Au3cHD6VCabqph4zxW1UMUJnBMG9+mPCEFP/bt/xGrJCsNlH/BGDxuHEP1g=
